name: issues actions

on:
  workflow_dispatch:
  
jobs:
  create-pr-by-issue:
    name: Create Pull Request
    runs-on: ubuntu-latest
    environment: GOOGLE_SHEET_DOC_ID

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Build
        run: |
          echo "GOOGLE_SHEET_DOC_ID ${{ secrets.GOOGLE_SHEET_DOC_ID }}"
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}"
          git config --local user.name "Frozen"
          git config --local user.email "1884084+xrdavies@users.noreply.github.com"
          yarn
          export GOOGLE_SHEET_DOC_ID=${{ secrets.GOOGLE_SHEET_DOC_ID }}
          export GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          export GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}
          node index.js
          
      - name: Commit changes
        run: |
          git add .
          git commit -m "Automatic build"
          git push --set-upstream origin master
